import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import NextThemeProvider from "@/providers/NextThemeProvider";
import Footer from "@/components/Footer";
import ScrollProvider from "@/providers/ScrollProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-screen  flex flex-col ">
        <NextThemeProvider>
          <ScrollProvider>
            <Navbar />

            <main className="flex-grow flex flex-col">{children}</main>
            <Footer />
          </ScrollProvider>
        </NextThemeProvider>
      </body>
    </html>
  );
}
